"""fix priority

Revision ID: 61d69d98dcaa
Revises: 3da2cd84a896
Create Date: 2026-08-27 20:52:11.505441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61d69d98dcaa'
down_revision: Union[str, Sequence[str], None] = '3da2cd84a896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes_user', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='priority'),
               nullable=False)
    op.alter_column('notes_user', 'created_at',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('notes_user', 'deadline',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('notes_user', 'deadline',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('notes_user', 'created_at',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('notes_user', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='priority'),
               nullable=True)
    # ### end Alembic commands ###
